[project]
name = "xtalbake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "peter.barrow.93@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.6.0",
    "matplotlib>=3.10.7",
    "pyqt6>=6.10.0",
    "pyserial",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
xtalbake-ui = "xtalbake.ui:main"
